-- Create BNPL Sessions Table
CREATE TABLE IF NOT EXISTS bnpl_sessions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  session_id VARCHAR(100) UNIQUE NOT NULL,
  store_id INT NOT NULL,
  store_order_id VARCHAR(255) NOT NULL,
  user_id INT NULL,
  customer_phone VARCHAR(20) NULL,
  customer_email VARCHAR(255) NULL,
  customer_name VARCHAR(255) NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  currency VARCHAR(3) DEFAULT 'JOD',
  installments_count INT DEFAULT 4,
  items JSON NULL,
  status ENUM('pending', 'approved', 'rejected', 'completed', 'cancelled', 'expired') DEFAULT 'pending',
  success_url TEXT NULL,
  cancel_url TEXT NULL,
  webhook_url TEXT NULL,
  metadata JSON NULL,
  expires_at TIMESTAMP NULL,
  approved_at TIMESTAMP NULL,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_session_id (session_id),
  INDEX idx_status (status),
  INDEX idx_store_id (store_id),
  INDEX idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
