// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCirAuivVMeGGvc_8w_7tt1w4JMM5-TR9w',
    appId: '1:166828864195:android:6537ed22c32eb14102a876',
    messagingSenderId: '166828864195',
    projectId: 'shahedapp',
    storageBucket: 'shahedapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVkxQcooQWB_6WPvbavz6UN-heRmJmTkg',
    appId: '1:166828864195:ios:e00fa55b919b59b402a876',
    messagingSenderId: '166828864195',
    projectId: 'shahedapp',
    storageBucket: 'shahedapp.firebasestorage.app',
    iosBundleId: 'com.shifracode.shahed',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbxNBtP9SywK2nniBqRbqR4_-vTHnF3-c',
    appId: '1:166828864195:web:15d4afd8426d1c9702a876',
    messagingSenderId: '166828864195',
    projectId: 'shahedapp',
    authDomain: 'shahedapp.firebaseapp.com',
    storageBucket: 'shahedapp.firebasestorage.app',
    measurementId: 'G-GV2JEBQK9Y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVkxQcooQWB_6WPvbavz6UN-heRmJmTkg',
    appId: '1:166828864195:ios:bf775d0b189ab78802a876',
    messagingSenderId: '166828864195',
    projectId: 'shahedapp',
    storageBucket: 'shahedapp.firebasestorage.app',
    iosBundleId: 'com.example.bnpl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbxNBtP9SywK2nniBqRbqR4_-vTHnF3-c',
    appId: '1:166828864195:web:73c4d4b7c262ff7902a876',
    messagingSenderId: '166828864195',
    projectId: 'shahedapp',
    authDomain: 'shahedapp.firebaseapp.com',
    storageBucket: 'shahedapp.firebasestorage.app',
    measurementId: 'G-Z9WRHK0B8Q',
  );

}